# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
#     - cron: "21 6,18 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: AkashSingh3031
          template: classic
          base: "header, activity, community, repositories, metadata"
          config_timezone: Asia/Kolkata
          plugin_achievements: yes      
          plugin_achievements_secrets: yes 
          plugin_achievements_threshold: C   
#           plugin_achievements_limit: 0
#           plugin_achievements_display: compact 
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_calendar: yes
          plugin_calendar_limit: 3
#           plugin_code: yes
#           plugin_code_languages: python, cpp
#           plugin_code_load: 400
#           plugin_contributors: yes
#           plugin_contributors_contributions: yes
#           plugin_contributors_sections: categories
#           plugin_contributors_categories: |
#             {
#               "🧩 Plugins / 🖼️ templates":["source/plugins/**", "source/templates/**"],
#               "📚 Documentation":["README.md", "**/README.md", "**/metadata.yml"],
#               "💻 Code (other)":["source/**", "Dockerfile"]
#             }
#           plugin_chess: yes
#           plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
#           plugin_chess_platform: lichess.org
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_fortune: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors : "rainbow"
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
#           plugin_licenses: yes
#           plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
#           plugin_licenses_legal: no
#           plugin_licenses_ratio: yes
          plugin_lines: yes
          plugin_music: no
          plugin_notable: yes
          plugin_notable_from: all
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
#           plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://prepverse.github.io/
          plugin_people: yes
          plugin_people_limit: 1000
          plugin_people_size: 28
          plugin_people_types: followers, following, contributors, stargazers, watchers
#           repositories_forks: yes
#           plugin_posts: yes
#           plugin_posts_source: dev.to
#           plugin_posts_limit: 2
#           plugin_posts_descriptions: yes
#           plugin_posts_covers: yes
#           plugin_posts_user: AkashSingh3031
          plugin_reactions: yes
          plugin_reactions_days: 14
          plugin_reactions_limit: 200
          plugin_reactions_details: percentage 
          plugin_repositories: yes
#           plugin_repositories_featured: AkashSingh3031/The-Complete-FAANG-Preparation
#           plugin_repositories_pinned: 2
#           plugin_screenshot: yes
#           plugin_screenshot_title: XKCD of the day
#           plugin_screenshot_url: https://xkcd.com
#           plugin_screenshot_selector: "#comic img"
#           plugin_sponsors: yes
#           plugin_sponsors_sections: goal, list
#           plugin_sponsors_past: yes
#           plugin_sponsorships: yes 
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_user: 18910829
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
#           plugin_stargazers_charts_type: graph
#           plugin_stargazers: yes
#           plugin_stargazers_charts: no
#           plugin_stargazers_worldmap: yes
#           plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
#           plugin_stargazers_worldmap_sample: 200
          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_year: 2023
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons
#           plugin_topics_mode: labels
          plugin_topics_sort: activity
#           plugin_tweets: yes
#           plugin_tweets_attachments: yes
#           plugin_tweets_limit: 1
#           plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
#           plugin_tweets_user: akashsingh3031
          
#       - name: Personal Metrics (detailed)
#         uses: lowlighter/metrics@master
#         with:
#           filename: metrics.detailed.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: "metadata"
#           config_timezone: Asia/Kolkata
#           plugin_followup: yes
#           plugin_followup_sections: user
#           plugin_gists: yes
#           plugin_languages: yes
#           plugin_languages_colors : "rainbow"
#           plugin_languages_details: bytes-size, percentage
#           plugin_languages_limit: 8
#           plugin_languages_recent_days: 14
#           plugin_languages_recent_load: 300
#           plugin_languages_sections: most-used
#           plugin_languages_threshold: 0%
#           plugin_pagespeed: yes
#           plugin_pagespeed_detailed: yes
#           plugin_pagespeed_url: https://prepverse.github.io/
#           plugin_pagespeed_screenshot: yes

