name: GitHub Metrics
on:
  schedule:
    - cron: "21 6,18 * * *"
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
          
      - name: Personal Metrics (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_gists: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_pagespeed_screenshot: yes
          plugin_posts: yes
          plugin_posts_source: medium.com
          plugin_posts_limit: 2
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_user: @akashsingh3031
          config_timezone: Asia/Kolkata
          plugin_languages_colors : "rainbow"
          plugin_languages_details: bytes-size, percentage
